name: Update Pricing Data

on:
  schedule:
    - cron: '0 20 * * *' # Run at 2 AM every Monday
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_pricing:
    runs-on: ubuntu-latest
    env:
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl pandas xlrd requests
          
      - name: Run pricing update script
        run: python pricing_update_github.py
